#Workflow configuration
name: Unvi Workflow
on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Start build
        run: mvn clean install
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: /target/**.jar
          name: unvi-project
      - name: Get artifact
        uses: actions/download-artifact@v3
        with:
          path: unvi-project
